PYTHON=python
DOCKER_COMPOSE=docker-compose

.PHONY: all build run test clean supervisor data_collector analyzer

all: build run

build:
    $(DOCKER_COMPOSE) build

run:
    $(DOCKER_COMPOSE) up -d

test:
    $(PYTHON) -m unittest discover -s tests

supervisor:
    $(PYTHON) src/Supervisor\ Agent.py

data_collector:
    $(PYTHON) src/Data\ Collector.py

analyzer:
    $(PYTHON) src/Analyzer\ Agent.py

clean:
    $(DOCKER_COMPOSE) down -v
